version: '3.8'

services:

  backend:
    build: ./backend
    env_file: 
      - ./backend/.env
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
      