version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 3000:${PORT}
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
      